name: 'bmkg_pipeline'
version: '2.0.0'
profile: 'bmkg_pipeline'

model-paths:  ["models"]
test-paths:   ["tests"]
macro-paths:  ["macros"]
seed-paths:   ["seeds"]
snapshot-paths: ["snapshots"]

clean-targets: ["target", "dbt_packages"]

models:
  bmkg_pipeline:
    staging:
      +materialized: incremental
      +schema: staging
    marts:
      +materialized: incremental
      +schema: marts
    monitoring:
      +materialized: table
      +schema: monitoring

vars:
  freshness_warn_hours: 2
  freshness_fail_hours: 12
